import React from "react";
import { FileSpreadsheet, Download, FileText, CheckCircle2 } from "lucide-react";
import { SalesReportItem } from "../../../types/salesTypes";

interface CommercialReportsTabProps {
  reports: SalesReportItem[];
}

export const CommercialReportsTab: React.FC<CommercialReportsTabProps> = ({ reports }) => {
  return (
    <div className="space-y-6">
      <div className="bg-white dark:bg-slate-900 p-5 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm">
        <h2 className="text-xl font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
          <FileSpreadsheet className="w-5 h-5 text-emerald-500" />
          Commercial & ESDM Shipment Reports
        </h2>
        <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
          Generate official monthly sales reports, ESDM RKAB commercial compliance documents, and customer sales statements.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {reports.map((rep) => (
          <div
            key={rep.id}
            className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-3 flex flex-col justify-between"
          >
            <div className="space-y-1">
              <div className="flex justify-between items-center">
                <span className="font-mono text-xs font-bold text-emerald-600 dark:text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded">
                  {rep.reportCode}
                </span>
                <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-blue-500/10 text-blue-600 dark:text-blue-400">
                  {rep.format}
                </span>
              </div>
              <h3 className="font-bold text-slate-900 dark:text-slate-100 text-sm">{rep.title}</h3>
              <p className="text-xs text-slate-500">Periode: {rep.period} • Generated by {rep.generatedBy}</p>
            </div>

            <div className="pt-3 border-t border-slate-100 dark:border-slate-800 flex justify-between items-center">
              <span className="text-xs text-emerald-600 font-semibold flex items-center gap-1">
                <CheckCircle2 className="w-3.5 h-3.5" /> Ready for Export
              </span>
              <button className="px-3 py-1.5 rounded-xl bg-emerald-500 text-slate-950 font-bold text-xs flex items-center gap-1.5 shadow">
                <Download className="w-3.5 h-3.5" /> Download {rep.format}
              </button>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
