// MINE SMART AI - AI Fuel Forecast, Reorder Recommendation & Report Center

import React, { useState } from "react";
import {
  Sparkles,
  AlertTriangle,
  Download,
  Calendar,
  FileText,
  TrendingDown,
  CheckCircle2,
  Clock,
  Send,
  Droplets,
  Building2,
  ShieldAlert
} from "lucide-react";
import {
  FuelForecast,
  FuelStockAlertItem
} from "../../types/fuelTypes";

interface FuelForecastAlertsReportsViewProps {
  forecasts: FuelForecast[];
  stockAlerts: FuelStockAlertItem[];
  onOpenAIAssistant: () => void;
}

export const FuelForecastAlertsReportsView: React.FC<FuelForecastAlertsReportsViewProps> = ({
  forecasts,
  stockAlerts,
  onOpenAIAssistant
}) => {
  const [activeTab, setActiveTab] = useState<"forecast" | "alerts" | "reports">("forecast");
  const [generatedReport, setGeneratedReport] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerateDailyReport = () => {
    setIsGenerating(true);
    setTimeout(() => {
      const reportText = `MINE SMART AI - DAILY FUEL REPORT
Date: 13 August 2026 | Site: Central Kalimantan Site 01

==================================================
1. EXECUTIVE SUMMARY
==================================================
Total Active Fuel Stock: 122,100 Liters (8.2 Operational Days)
Total Dispensed Today: 26,400 Liters
Total Received Today: 48,000 Liters (Pertamina Patra Niaga & AKR)
Overall Fuel Efficiency: 0.81 L/Ton (Coal) & 0.51 L/BCM (OB)

==================================================
2. STOCK & RECONCILIATION SUMMARY
==================================================
Opening Stock: 120,500 Liters
Receiving (+): 48,000 Liters
Dispensing (-): 26,400 Liters
Adjustments (+/-): -120 Liters (Meter Calibration Correction)
Expected Closing Stock: 142,380 Liters
Physical Closing Stock: 142,250 Liters
Net Stock Variance: -130 Liters (-0.23% - Within Normal Limit)

==================================================
3. FUEL EFFICIENCY & TOP CONSUMERS
==================================================
- Fleet Avg Fuel / Hour: 43.1 L/Hr
- Fleet Avg Fuel / Ton: 0.81 L/Ton
- Fleet Avg Fuel / KM: 1.95 L/km

Top Consumers Today:
1. EX-102 (Komatsu PC2000): 920 Liters (93.88 L/Hr)
2. EX-101 (CAT 6020B): 850 Liters (85.0 L/Hr)
3. HT-203 (Volvo FMX440): 410 Liters (1.078 L/Ton)

==================================================
4. ANOMALIES & FUEL LOSS INVESTIGATION
==================================================
Active Anomalies Detected: 2 Units (HT-203 Fuel/Ton Spike, EX-102 High Fuel/Hour)
Loss Alert FLA-01: Resolved (Variance -130L attributed to flowmeter drift & thermal expansion)
Unauthorized Theft Indication: NONE DETECTED

==================================================
5. AI FORECAST & REORDER RECOMMENDATION
==================================================
Estimated End-of-Week Consumption: 98,500 Liters
Recommended Reorder Date: 16 August 2026
Recommended Purchase Volume: 32,000 Liters (BioSolar B35)

Report Generated By: Mine Smart AI Engine
Quality Status: VERIFIED & AUDITED`;
      setGeneratedReport(reportText);
      setIsGenerating(false);
    }, 1000);
  };

  const handleExportCSV = () => {
    const csvContent = "data:text/csv;charset=utf-8," +
      "Date,Type,Location,Volume_Liter,Status\n" +
      "2026-08-13,Receiving,Main Storage Tank 01,32000,Posted\n" +
      "2026-08-13,Receiving,Pit A Station,16000,Approved\n" +
      "2026-08-13,Dispensing,HT-201,380,Validated\n" +
      "2026-08-13,Dispensing,HT-202,395,Validated\n" +
      "2026-08-13,Dispensing,EX-101,850,Validated\n";
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `Daily_Fuel_Report_20260813.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="space-y-6">
      {/* Subtabs */}
      <div className="flex items-center gap-2 bg-slate-900 border border-slate-800 p-4 rounded-2xl shadow-lg overflow-x-auto">
        <button
          onClick={() => setActiveTab("forecast")}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
            activeTab === "forecast" ? "bg-amber-500 text-slate-950 shadow-md" : "bg-slate-800 text-slate-300 hover:bg-slate-700"
          }`}
        >
          AI Fuel Forecast & Reorder Recommendations
        </button>
        <button
          onClick={() => setActiveTab("alerts")}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
            activeTab === "alerts" ? "bg-amber-500 text-slate-950 shadow-md" : "bg-slate-800 text-slate-300 hover:bg-slate-700"
          }`}
        >
          Fuel Stock Alerts ({stockAlerts.length})
        </button>
        <button
          onClick={() => setActiveTab("reports")}
          className={`px-4 py-2 rounded-xl text-xs font-bold transition-all ${
            activeTab === "reports" ? "bg-amber-500 text-slate-950 shadow-md" : "bg-slate-800 text-slate-300 hover:bg-slate-700"
          }`}
        >
          AI Daily Fuel Report Generator
        </button>
      </div>

      {/* TAB 1: AI FORECAST */}
      {activeTab === "forecast" && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {forecasts.map(f => (
              <div key={f.id} className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4">
                <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                  <div>
                    <h3 className="text-base font-bold text-amber-400">Proyeksi Konsumsi: {f.period}</h3>
                    <p className="text-xs text-slate-400 mt-0.5">Confidence Level: {(f.confidence * 100).toFixed(0)}%</p>
                  </div>
                  <span className="px-2.5 py-1 rounded bg-amber-500/20 text-amber-300 border border-amber-500/30 text-xs font-mono font-bold">
                    [Estimated / Forecast]
                  </span>
                </div>

                <div className="grid grid-cols-2 gap-3 text-xs">
                  <div className="p-3 bg-slate-950 rounded-xl border border-slate-800">
                    <div className="text-slate-400">Projected Consumption</div>
                    <div className="text-lg font-black text-amber-400 font-mono mt-0.5">
                      {f.projectedConsumption.toLocaleString()} L
                    </div>
                  </div>

                  <div className="p-3 bg-slate-950 rounded-xl border border-slate-800">
                    <div className="text-slate-400">Expected Closing Stock</div>
                    <div className="text-lg font-black text-emerald-400 font-mono mt-0.5">
                      {f.expectedClosingStock.toLocaleString()} L
                    </div>
                  </div>
                </div>

                <div className="p-3.5 bg-slate-950/80 border border-slate-800 rounded-xl text-xs space-y-1">
                  <div className="font-bold text-slate-200">Rekomendasi Pembelian (Reorder Recommendation):</div>
                  <p className="text-slate-300">{f.recommendation}</p>
                  <div className="mt-2 pt-2 border-t border-slate-800 flex items-center justify-between font-mono text-[11px] text-amber-300">
                    <span>Reorder Date: {f.reorderDate}</span>
                    <span>Reorder Vol: {f.reorderQuantity.toLocaleString()} L</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* TAB 2: ALERTS */}
      {activeTab === "alerts" && (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-4">
          <h3 className="text-base font-bold text-slate-100 flex items-center gap-2">
            <AlertTriangle className="w-5 h-5 text-amber-400" />
            Active Fuel Stock & Operational Alerts
          </h3>

          <div className="space-y-3">
            {stockAlerts.map(a => (
              <div key={a.id} className="p-4 bg-slate-950 border border-slate-800 rounded-xl flex items-center justify-between text-xs">
                <div>
                  <div className="font-bold text-amber-300 flex items-center gap-2">
                    <span>{a.tankName}</span>
                    <span className="text-[10px] px-2 py-0.5 rounded bg-amber-500/20 text-amber-300 border border-amber-500/30">
                      {a.alertType}
                    </span>
                  </div>
                  <p className="text-slate-300 mt-1">{a.message}</p>
                  <div className="text-[10px] text-slate-500 font-mono mt-1">{a.timestamp}</div>
                </div>

                <span className="px-3 py-1 bg-amber-500/20 text-amber-300 border border-amber-500/30 rounded-lg font-bold">
                  {a.severity}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* TAB 3: REPORTS GENERATOR */}
      {activeTab === "reports" && (
        <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <div>
              <h3 className="text-lg font-bold text-slate-100 flex items-center gap-2">
                <FileText className="w-5 h-5 text-amber-400" />
                AI Daily Fuel Report Generator
              </h3>
              <p className="text-xs text-slate-400 mt-0.5">
                Generate laporan konsumsi, stok, rekonsiliasi, dan AI insight harian secara otomatis
              </p>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleGenerateDailyReport}
                disabled={isGenerating}
                className="bg-amber-500 hover:bg-amber-600 text-slate-950 font-bold px-4 py-2.5 rounded-xl text-xs flex items-center gap-2 shadow-md transition-all disabled:opacity-50"
              >
                <Sparkles className="w-4 h-4" />
                {isGenerating ? "Generating Report..." : "Generate AI Daily Report"}
              </button>

              <button
                onClick={handleExportCSV}
                className="bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700 px-4 py-2.5 rounded-xl text-xs font-bold flex items-center gap-2 transition-all"
              >
                <Download className="w-4 h-4 text-emerald-400" />
                Export CSV Data
              </button>
            </div>
          </div>

          {generatedReport ? (
            <div className="p-5 bg-slate-950 border border-slate-800 rounded-2xl shadow-inner font-mono text-xs text-slate-200 leading-relaxed whitespace-pre-wrap">
              {generatedReport}
            </div>
          ) : (
            <div className="p-12 text-center text-slate-500 bg-slate-950/60 rounded-2xl border border-slate-800/80">
              <FileText className="w-12 h-12 mx-auto mb-3 opacity-30 text-amber-400" />
              <p className="text-sm font-medium">Klik tombol "Generate AI Daily Report" untuk memuat laporan lengkap.</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
