// MINE SMART AI - Geology Data Repository & State Manager
// Comprehensive Repository covering Borehole, Collar, Survey, Lithology, Seam, Sample, Assay, Coal Quality, and AI Geology datasets

import {
  Borehole,
  Collar,
  DownholeSurveyRecord,
  LithologyCatalogItem,
  LithologyRecord,
  SeamMaster,
  SeamIntersection,
  SampleRecord,
  AssayRecord,
  CoalQualityProfile,
  GeologicalDatabaseVersion,
  CorePhotoRecord,
  AIGeologySeamCorrelation,
  AIGeologyQualityPrediction,
  AIGeologyAnomaly,
  AIGeologyInterpretation,
  AIGeologyDataValidation,
  AIGeologyResourceEstimation,
} from "../../types/geologyTypes";

export class GeologyRepository {
  // 1. Boreholes
  private static boreholes: Borehole[] = [
    {
      id: "bh-001",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeCode: "BH-SGT-001",
      pitId: "pit-01",
      pitName: "Pit 1 South",
      projectId: "proj-exp-2026",
      status: "VALIDATED",
      drillingType: "DIAMOND_CORE",
      plannedDepth: 180,
      actualDepth: 175.5,
      startDate: "2026-03-01",
      completionDate: "2026-03-05",
      contractor: "PT GeoDrill Indonesia",
      drillingRig: "Rig Delta-02",
      drillerName: "Bambang Sujarwo",
      coreDiameterMm: 63.5, // HQ
      overallRecoveryPercent: 98.6,
      waterTableDepthM: 14.2,
      remarks: "Pengeboran inti lengkap 100% recovery pada Seam A dan Seam B.",
      validationStatus: "VALID",
      seamCount: 3,
      sampleCount: 6,
      createdAt: "2026-03-01T08:00:00Z",
      updatedAt: "2026-03-10T08:00:00Z",
    },
    {
      id: "bh-002",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeCode: "BH-SGT-002",
      pitId: "pit-01",
      pitName: "Pit 1 South",
      projectId: "proj-exp-2026",
      status: "VALIDATED",
      drillingType: "DIAMOND_CORE",
      plannedDepth: 160,
      actualDepth: 162.0,
      startDate: "2026-03-06",
      completionDate: "2026-03-10",
      contractor: "PT GeoDrill Indonesia",
      drillingRig: "Rig Delta-02",
      drillerName: "Bambang Sujarwo",
      coreDiameterMm: 63.5,
      overallRecoveryPercent: 97.4,
      waterTableDepthM: 12.8,
      remarks: "Interseksi batubara tebal Seam A pada kedalaman 45m.",
      validationStatus: "VALID",
      seamCount: 3,
      sampleCount: 5,
      createdAt: "2026-03-06T08:00:00Z",
      updatedAt: "2026-03-15T08:00:00Z",
    },
    {
      id: "bh-003",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeCode: "BH-SGT-003",
      pitId: "pit-01",
      pitName: "Pit 1 South",
      projectId: "proj-exp-2026",
      status: "COMPLETED",
      drillingType: "REVERSE_CIRCULATION",
      plannedDepth: 150,
      actualDepth: 148.0,
      startDate: "2026-04-01",
      completionDate: "2026-04-03",
      contractor: "PT Nusantara Explorasi",
      drillingRig: "Rig RC-05",
      drillerName: "Agus Hermawan",
      overallRecoveryPercent: 95.0,
      waterTableDepthM: 15.5,
      remarks: "Pengeboran RC untuk infill drilling kerapatan 50m.",
      validationStatus: "VALID",
      seamCount: 2,
      sampleCount: 4,
      createdAt: "2026-04-01T08:00:00Z",
      updatedAt: "2026-04-10T08:00:00Z",
    },
    {
      id: "bh-004",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeCode: "BH-SGT-004",
      pitId: "pit-02",
      pitName: "Pit 2 North",
      projectId: "proj-exp-2026",
      status: "DRILLING",
      drillingType: "DIAMOND_CORE",
      plannedDepth: 200,
      actualDepth: 112.5,
      startDate: "2026-08-01",
      contractor: "PT GeoDrill Indonesia",
      drillingRig: "Rig Delta-01",
      drillerName: "Suryono",
      coreDiameterMm: 63.5,
      overallRecoveryPercent: 92.0,
      remarks: "Sedang berlangsung pengeboran inti penjelajah utara.",
      validationStatus: "WARNING",
      seamCount: 2,
      sampleCount: 2,
      createdAt: "2026-08-01T08:00:00Z",
      updatedAt: "2026-08-12T08:00:00Z",
    },
    {
      id: "bh-005",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeCode: "BH-SGT-005",
      pitId: "pit-02",
      pitName: "Pit 2 North",
      projectId: "proj-exp-2026",
      status: "VALIDATED",
      drillingType: "DIAMOND_CORE",
      plannedDepth: 190,
      actualDepth: 188.0,
      startDate: "2026-05-10",
      completionDate: "2026-05-15",
      contractor: "PT GeoDrill Indonesia",
      drillingRig: "Rig Delta-01",
      coreDiameterMm: 63.5,
      overallRecoveryPercent: 99.1,
      remarks: "Seam A terpantau membelah (split) menjadi Seam A1 dan A2.",
      validationStatus: "VALID",
      seamCount: 4,
      sampleCount: 6,
      createdAt: "2026-05-10T08:00:00Z",
      updatedAt: "2026-05-20T08:00:00Z",
    },
  ];

  // 2. Collars
  private static collars: Collar[] = [
    {
      id: "col-001",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      latitude: -0.4925,
      longitude: 117.1422,
      easting: 515820.4,
      northing: 9945620.8,
      elevation: 85.4,
      demLiDARElevation: 85.35,
      elevationDelta: 0.05,
      azimuth: 0,
      dip: -90,
      totalDepth: 175.5,
      coordinateSystem: {
        epsg: "EPSG:32750",
        datum: "WGS84",
        zone: "Zone 50S",
        hemisphere: "SOUTH",
      },
      surveyMethod: "RTK_GPS",
      surveyDate: "2026-03-05",
      accuracyMeters: 0.02,
      surveyorName: "Rudi Hartono (Chief Surveyor)",
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "col-002",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-002",
      boreholeCode: "BH-SGT-002",
      latitude: -0.4938,
      longitude: 117.1445,
      easting: 516075.2,
      northing: 9945476.5,
      elevation: 92.1,
      demLiDARElevation: 92.05,
      elevationDelta: 0.05,
      azimuth: 0,
      dip: -90,
      totalDepth: 162.0,
      coordinateSystem: {
        epsg: "EPSG:32750",
        datum: "WGS84",
        zone: "Zone 50S",
        hemisphere: "SOUTH",
      },
      surveyMethod: "RTK_GPS",
      surveyDate: "2026-03-10",
      accuracyMeters: 0.02,
      surveyorName: "Rudi Hartono",
      validationStatus: "VALID",
      createdAt: "2026-03-10T08:00:00Z",
      updatedAt: "2026-03-10T08:00:00Z",
    },
    {
      id: "col-003",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-003",
      boreholeCode: "BH-SGT-003",
      latitude: -0.4951,
      longitude: 117.1468,
      easting: 516330.1,
      northing: 9945332.1,
      elevation: 78.6,
      demLiDARElevation: 78.52,
      elevationDelta: 0.08,
      azimuth: 0,
      dip: -90,
      totalDepth: 148.0,
      coordinateSystem: {
        epsg: "EPSG:32750",
        datum: "WGS84",
        zone: "Zone 50S",
        hemisphere: "SOUTH",
      },
      surveyMethod: "TOTAL_STATION",
      surveyDate: "2026-04-03",
      accuracyMeters: 0.05,
      surveyorName: "Dedi Setiawan",
      validationStatus: "VALID",
      createdAt: "2026-04-03T08:00:00Z",
      updatedAt: "2026-04-03T08:00:00Z",
    },
    {
      id: "col-004",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-004",
      boreholeCode: "BH-SGT-004",
      latitude: -0.4862,
      longitude: 117.1528,
      easting: 517000.0,
      northing: 9946300.0,
      elevation: 110.0,
      demLiDARElevation: 107.8, // 2.2m discrepancy!
      elevationDelta: 2.2,
      azimuth: 0,
      dip: -90,
      totalDepth: 112.5,
      coordinateSystem: {
        epsg: "EPSG:32750",
        datum: "WGS84",
        zone: "Zone 50S",
        hemisphere: "SOUTH",
      },
      surveyMethod: "HANDHELD_GPS",
      surveyDate: "2026-08-01",
      accuracyMeters: 1.5,
      surveyorName: "Asisten Geologi",
      validationStatus: "WARNING",
      validationMessages: ["Akurasi GPS genggam > 1.0m, elevasi collar selisih 2.2m dibanding DTM LiDAR."],
      createdAt: "2026-08-01T08:00:00Z",
      updatedAt: "2026-08-01T08:00:00Z",
    },
    {
      id: "col-005",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-005",
      boreholeCode: "BH-SGT-005",
      latitude: -0.4880,
      longitude: 117.1500,
      easting: 516680.5,
      northing: 9946100.2,
      elevation: 98.4,
      demLiDARElevation: 98.38,
      elevationDelta: 0.02,
      azimuth: 0,
      dip: -90,
      totalDepth: 188.0,
      coordinateSystem: {
        epsg: "EPSG:32750",
        datum: "WGS84",
        zone: "Zone 50S",
        hemisphere: "SOUTH",
      },
      surveyMethod: "RTK_GPS",
      surveyDate: "2026-05-15",
      accuracyMeters: 0.02,
      surveyorName: "Rudi Hartono",
      validationStatus: "VALID",
      createdAt: "2026-05-15T08:00:00Z",
      updatedAt: "2026-05-15T08:00:00Z",
    },
  ];

  // 3. Downhole Surveys (Deviation)
  private static surveys: DownholeSurveyRecord[] = [
    {
      id: "srv-001",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      measuredDepthM: 0,
      inclinationDipDeg: -90.0,
      azimuthDeg: 0,
      trueVerticalDepthM: 0,
      deltaEastingM: 0,
      deltaNorthingM: 0,
      doglegSeverityDegPer30M: 0,
      surveyTool: "GYRO_SURVEY",
      surveyor: "GeoSurv Specialist",
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "srv-002",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      measuredDepthM: 60.0,
      inclinationDipDeg: -89.4,
      azimuthDeg: 88.5,
      trueVerticalDepthM: 59.98,
      deltaEastingM: 0.32,
      deltaNorthingM: 0.04,
      doglegSeverityDegPer30M: 0.3,
      surveyTool: "GYRO_SURVEY",
      surveyor: "GeoSurv Specialist",
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "srv-003",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      measuredDepthM: 120.0,
      inclinationDipDeg: -88.9,
      azimuthDeg: 92.1,
      trueVerticalDepthM: 119.93,
      deltaEastingM: 0.85,
      deltaNorthingM: 0.08,
      doglegSeverityDegPer30M: 0.25,
      surveyTool: "GYRO_SURVEY",
      surveyor: "GeoSurv Specialist",
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "srv-004",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      measuredDepthM: 175.5,
      inclinationDipDeg: -88.2,
      azimuthDeg: 95.0,
      trueVerticalDepthM: 175.38,
      deltaEastingM: 1.54,
      deltaNorthingM: 0.12,
      doglegSeverityDegPer30M: 0.35,
      surveyTool: "GYRO_SURVEY",
      surveyor: "GeoSurv Specialist",
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "srv-005",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-002",
      boreholeCode: "BH-SGT-002",
      measuredDepthM: 162.0,
      inclinationDipDeg: -89.0,
      azimuthDeg: 45.0,
      trueVerticalDepthM: 161.92,
      deltaEastingM: 0.98,
      deltaNorthingM: 0.95,
      doglegSeverityDegPer30M: 0.2,
      surveyTool: "MAGNETIC_MULTI_SHOT",
      surveyor: "GeoSurv Specialist",
      validationStatus: "VALID",
      createdAt: "2026-03-10T08:00:00Z",
      updatedAt: "2026-03-10T08:00:00Z",
    },
  ];

  // 4. Lithology Catalog & Logs
  private static lithologyCatalog: LithologyCatalogItem[] = [
    {
      id: "lc-01",
      companyId: "comp-01",
      code: "COAL",
      name: "Coal / Batubara",
      category: "COAL",
      colorHex: "#111827", // Black
      patternStyle: "solid",
      description: "Batubara hitam mengkilap, terlipat rapat, pecahan konkoidal.",
      createdAt: "2026-01-01T08:00:00Z",
      updatedAt: "2026-01-01T08:00:00Z",
    },
    {
      id: "lc-02",
      companyId: "comp-01",
      code: "MDST",
      name: "Mudstone / Batu Lumpur",
      category: "SEDIMENTARY",
      colorHex: "#64748b", // Slate Gray
      patternStyle: "dashed",
      description: "Batu lumpur abu-abu gelap, masif, mengandung fosil tumbuhan.",
      createdAt: "2026-01-01T08:00:00Z",
      updatedAt: "2026-01-01T08:00:00Z",
    },
    {
      id: "lc-03",
      companyId: "comp-01",
      code: "SDST",
      name: "Sandstone / Batu Pasir",
      category: "SEDIMENTARY",
      colorHex: "#d97706", // Amber Brown
      patternStyle: "dots",
      description: "Batu pasir butir halus-sedang, kuarsa dominan, perlapisan silang.",
      createdAt: "2026-01-01T08:00:00Z",
      updatedAt: "2026-01-01T08:00:00Z",
    },
    {
      id: "lc-04",
      companyId: "comp-01",
      code: "SLST",
      name: "Siltstone / Batu Lanau",
      category: "SEDIMENTARY",
      colorHex: "#94a3b8", // Light Slate
      patternStyle: "stripes",
      description: "Batu lanau abu-abu terang, laminasi paralel, karbonan.",
      createdAt: "2026-01-01T08:00:00Z",
      updatedAt: "2026-01-01T08:00:00Z",
    },
    {
      id: "lc-05",
      companyId: "comp-01",
      code: "CSHL",
      name: "Carbonaceous Shale / Serpih Karbonan",
      category: "SEDIMENTARY",
      colorHex: "#334155", // Charcoal Gray
      patternStyle: "fine-lines",
      description: "Serpih kaya materi organik, getas, transisi ke roof/floor batubara.",
      createdAt: "2026-01-01T08:00:00Z",
      updatedAt: "2026-01-01T08:00:00Z",
    },
    {
      id: "lc-06",
      companyId: "comp-01",
      code: "SOIL",
      name: "Top Soil & Subsoil",
      category: "WEATHERED",
      colorHex: "#854d0e", // Rich Soil Brown
      patternStyle: "grain",
      description: "Tanah penutup humus dan lempung lapuk permukaan.",
      createdAt: "2026-01-01T08:00:00Z",
      updatedAt: "2026-01-01T08:00:00Z",
    },
  ];

  private static lithologies: LithologyRecord[] = [
    {
      id: "lit-001",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      fromDepth: 0,
      toDepth: 4.5,
      thickness: 4.5,
      lithologyCode: "SOIL",
      lithologyName: "Top Soil & Alluvium",
      description: "Tanah pucuk cokelat tua kaya humus dan lanau lempungan.",
      weatheringGrade: "COMPLETE",
      color: "Brown",
      grainSize: "Fine to Medium",
      hardness: "VERY_SOFT",
      coreRecoveryPercent: 95.0,
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "lit-002",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      fromDepth: 4.5,
      toDepth: 42.0,
      thickness: 37.5,
      lithologyCode: "SDST",
      lithologyName: "Sandstone (Overburden)",
      description: "Batu pasir butir sedang kuarsa, kompak, perlapisan silang siur.",
      weatheringGrade: "SLIGHTLY",
      color: "Light Gray",
      grainSize: "Medium Sand",
      hardness: "MEDIUM_HARD",
      coreRecoveryPercent: 99.2,
      rqdPercent: 88.0,
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "lit-003",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      fromDepth: 42.0,
      toDepth: 52.0,
      thickness: 10.0,
      lithologyCode: "CSHL",
      lithologyName: "Carbonaceous Shale (Immediate Roof)",
      description: "Serpih hitam kelabu getas, kaya material karbon dan laminasi pirit.",
      weatheringGrade: "UNWEATHERED",
      color: "Dark Gray to Black",
      grainSize: "Clay to Silt",
      hardness: "SOFT",
      coreRecoveryPercent: 98.0,
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "lit-004",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      fromDepth: 52.0,
      toDepth: 64.8,
      thickness: 12.8,
      lithologyCode: "COAL",
      lithologyName: "Coal (Seam Sangatta A)",
      description: "Batubara hitam mengkilap (bright banded coal), padat, pecahan konkoidal.",
      weatheringGrade: "UNWEATHERED",
      color: "Black",
      grainSize: "Amorphous Organic",
      hardness: "MEDIUM_HARD",
      coreRecoveryPercent: 100.0,
      rqdPercent: 96.0,
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "lit-005",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      fromDepth: 64.8,
      toDepth: 98.0,
      thickness: 33.2,
      lithologyCode: "MDST",
      lithologyName: "Mudstone (Interburden)",
      description: "Batu lumpur masif abu-abu gelap, sisipan siderit tipis.",
      weatheringGrade: "UNWEATHERED",
      color: "Gray",
      grainSize: "Clay",
      hardness: "MEDIUM_HARD",
      coreRecoveryPercent: 97.5,
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "lit-006",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      fromDepth: 98.0,
      toDepth: 104.5,
      thickness: 6.5,
      lithologyCode: "COAL",
      lithologyName: "Coal (Seam Sangatta B)",
      description: "Batubara semi-bright dengan sisipan parting lempung karbonan 0.15m.",
      weatheringGrade: "UNWEATHERED",
      color: "Black",
      grainSize: "Amorphous Organic",
      hardness: "MEDIUM_HARD",
      coreRecoveryPercent: 99.0,
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "lit-007",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      fromDepth: 104.5,
      toDepth: 175.5,
      thickness: 71.0,
      lithologyCode: "SDST",
      lithologyName: "Sandstone (Basement Floor)",
      description: "Batu pasir kasar konglomeratan masif.",
      weatheringGrade: "UNWEATHERED",
      color: "Grayish White",
      grainSize: "Coarse Sand",
      hardness: "HARD",
      coreRecoveryPercent: 98.5,
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
  ];

  // 5. Seam Masters & Intersections
  private static seamMasters: SeamMaster[] = [
    {
      id: "sm-01",
      companyId: "comp-01",
      seamCode: "SEAM_A",
      seamName: "Seam Sangatta A (Main Seam)",
      targetPitId: "pit-01",
      averageThicknessMeters: 12.4,
      dipAngleDeg: 14.5,
      dipDirectionDeg: 115,
      coalRank: "SUB_BITUMINOUS_A",
      qualityGrade: "PREMIUM_EXPORT",
      colorBadge: "#10b981", // Emerald
      createdAt: "2026-01-01T08:00:00Z",
      updatedAt: "2026-01-01T08:00:00Z",
    },
    {
      id: "sm-02",
      companyId: "comp-01",
      seamCode: "SEAM_B",
      seamName: "Seam Sangatta B (Middle Seam)",
      targetPitId: "pit-01",
      averageThicknessMeters: 6.8,
      dipAngleDeg: 14.0,
      dipDirectionDeg: 115,
      coalRank: "SUB_BITUMINOUS_B",
      qualityGrade: "HIGH_CV",
      colorBadge: "#3b82f6", // Blue
      createdAt: "2026-01-01T08:00:00Z",
      updatedAt: "2026-01-01T08:00:00Z",
    },
    {
      id: "sm-03",
      companyId: "comp-01",
      seamCode: "SEAM_C",
      seamName: "Seam Sangatta C (Lower Seam)",
      targetPitId: "pit-01",
      averageThicknessMeters: 4.2,
      dipAngleDeg: 13.8,
      dipDirectionDeg: 118,
      coalRank: "SUB_BITUMINOUS_B",
      qualityGrade: "MEDIUM_CV",
      colorBadge: "#f59e0b", // Amber
      createdAt: "2026-01-01T08:00:00Z",
      updatedAt: "2026-01-01T08:00:00Z",
    },
  ];

  private static seams: SeamIntersection[] = [
    {
      id: "smi-001",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      seamId: "sm-01",
      seamCode: "SEAM_A",
      seamName: "Seam Sangatta A",
      fromDepth: 52.0,
      toDepth: 64.8,
      apparentThickness: 12.8,
      trueThickness: 12.38,
      elevation: 27.0,
      roofElevation: 33.4,
      floorElevation: 20.6,
      partingThicknessM: 0.0,
      coalRecoveryPercent: 100.0,
      qualityStatus: "TESTED",
      validationStatus: "VALID",
      correlationConfidenceScore: 98.5,
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "smi-002",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      seamId: "sm-02",
      seamCode: "SEAM_B",
      seamName: "Seam Sangatta B",
      fromDepth: 98.0,
      toDepth: 104.5,
      apparentThickness: 6.5,
      trueThickness: 6.29,
      elevation: -15.8,
      roofElevation: -12.6,
      floorElevation: -19.1,
      partingThicknessM: 0.15,
      coalRecoveryPercent: 99.0,
      qualityStatus: "TESTED",
      validationStatus: "VALID",
      correlationConfidenceScore: 96.0,
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-05T08:00:00Z",
    },
    {
      id: "smi-003",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-002",
      boreholeCode: "BH-SGT-002",
      seamId: "sm-01",
      seamCode: "SEAM_A",
      seamName: "Seam Sangatta A",
      fromDepth: 45.2,
      toDepth: 57.6,
      apparentThickness: 12.4,
      trueThickness: 12.01,
      elevation: 40.7,
      roofElevation: 46.9,
      floorElevation: 34.5,
      partingThicknessM: 0.0,
      coalRecoveryPercent: 98.5,
      qualityStatus: "TESTED",
      validationStatus: "VALID",
      correlationConfidenceScore: 99.0,
      createdAt: "2026-03-10T08:00:00Z",
      updatedAt: "2026-03-10T08:00:00Z",
    },
    {
      id: "smi-004",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-002",
      boreholeCode: "BH-SGT-002",
      seamId: "sm-02",
      seamCode: "SEAM_B",
      seamName: "Seam Sangatta B",
      fromDepth: 91.0,
      toDepth: 98.0,
      apparentThickness: 7.0,
      trueThickness: 6.78,
      elevation: -2.4,
      roofElevation: 1.1,
      floorElevation: -5.9,
      partingThicknessM: 0.1,
      coalRecoveryPercent: 97.5,
      qualityStatus: "TESTED",
      validationStatus: "VALID",
      correlationConfidenceScore: 95.0,
      createdAt: "2026-03-10T08:00:00Z",
      updatedAt: "2026-03-10T08:00:00Z",
    },
  ];

  // 6. Samples
  private static samples: SampleRecord[] = [
    {
      id: "smp-001",
      companyId: "comp-01",
      siteId: "site-01",
      sampleCode: "SGT-SMP-001",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      seamId: "sm-01",
      seamCode: "SEAM_A",
      fromDepth: 52.0,
      toDepth: 58.0,
      sampleThicknessM: 6.0,
      sampleType: "CORE",
      sampleDate: "2026-03-05",
      weightKg: 8.5,
      laboratory: "PT Sucofindo Samarinda",
      custodyStatus: "VALIDATED",
      chainOfCustodyLogs: [
        { timestamp: "2026-03-05T10:00:00Z", status: "COLLECTED", handlerName: "Budi Geologist", location: "Rig Delta-02" },
        { timestamp: "2026-03-06T08:00:00Z", status: "PREPARED", handlerName: "Rian Core House", location: "Core House Sangatta" },
        { timestamp: "2026-03-07T14:00:00Z", status: "DISPATCHED", handlerName: "Ekspedisi Geologi", location: "Trans Samarinda" },
        { timestamp: "2026-03-08T09:00:00Z", status: "RECEIVED", handlerName: "Lab Staff Sucofindo", location: "Lab Samarinda" },
        { timestamp: "2026-03-12T16:00:00Z", status: "ANALYZED", handlerName: "Chief Chemist", location: "Lab Samarinda" },
        { timestamp: "2026-03-14T10:00:00Z", status: "VALIDATED", handlerName: "Senior Geologist", location: "Mine Site" },
      ],
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
    {
      id: "smp-002",
      companyId: "comp-01",
      siteId: "site-01",
      sampleCode: "SGT-SMP-002",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      seamId: "sm-01",
      seamCode: "SEAM_A",
      fromDepth: 58.0,
      toDepth: 64.8,
      sampleThicknessM: 6.8,
      sampleType: "CORE",
      sampleDate: "2026-03-05",
      weightKg: 9.2,
      laboratory: "PT Sucofindo Samarinda",
      custodyStatus: "VALIDATED",
      chainOfCustodyLogs: [
        { timestamp: "2026-03-05T10:00:00Z", status: "COLLECTED", handlerName: "Budi Geologist", location: "Rig Delta-02" },
        { timestamp: "2026-03-12T16:00:00Z", status: "ANALYZED", handlerName: "Chief Chemist", location: "Lab Samarinda" },
        { timestamp: "2026-03-14T10:00:00Z", status: "VALIDATED", handlerName: "Senior Geologist", location: "Mine Site" },
      ],
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
    {
      id: "smp-003",
      companyId: "comp-01",
      siteId: "site-01",
      sampleCode: "SGT-SMP-003",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      seamId: "sm-02",
      seamCode: "SEAM_B",
      fromDepth: 98.0,
      toDepth: 104.5,
      sampleThicknessM: 6.5,
      sampleType: "CORE",
      sampleDate: "2026-03-05",
      weightKg: 8.9,
      laboratory: "PT Sucofindo Samarinda",
      custodyStatus: "VALIDATED",
      chainOfCustodyLogs: [
        { timestamp: "2026-03-05T10:00:00Z", status: "COLLECTED", handlerName: "Budi Geologist", location: "Rig Delta-02" },
        { timestamp: "2026-03-12T16:00:00Z", status: "ANALYZED", handlerName: "Chief Chemist", location: "Lab Samarinda" },
        { timestamp: "2026-03-14T10:00:00Z", status: "VALIDATED", handlerName: "Senior Geologist", location: "Mine Site" },
      ],
      validationStatus: "VALID",
      createdAt: "2026-03-05T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
    {
      id: "smp-004",
      companyId: "comp-01",
      siteId: "site-01",
      sampleCode: "SGT-SMP-004",
      boreholeId: "bh-002",
      boreholeCode: "BH-SGT-002",
      seamId: "sm-01",
      seamCode: "SEAM_A",
      fromDepth: 45.2,
      toDepth: 57.6,
      sampleThicknessM: 12.4,
      sampleType: "CORE",
      sampleDate: "2026-03-10",
      weightKg: 16.4,
      laboratory: "PT Geoservices Balikpapan",
      custodyStatus: "VALIDATED",
      chainOfCustodyLogs: [
        { timestamp: "2026-03-10T11:00:00Z", status: "COLLECTED", handlerName: "Budi Geologist", location: "Rig Delta-02" },
        { timestamp: "2026-03-16T16:00:00Z", status: "ANALYZED", handlerName: "Chief Chemist", location: "Lab Balikpapan" },
        { timestamp: "2026-03-18T10:00:00Z", status: "VALIDATED", handlerName: "Senior Geologist", location: "Mine Site" },
      ],
      validationStatus: "VALID",
      createdAt: "2026-03-10T08:00:00Z",
      updatedAt: "2026-03-18T08:00:00Z",
    },
  ];

  // 7. Assays
  private static assays: AssayRecord[] = [
    {
      id: "asy-001",
      companyId: "comp-01",
      siteId: "site-01",
      sampleId: "smp-001",
      sampleCode: "SGT-SMP-001",
      boreholeCode: "BH-SGT-001",
      laboratory: "PT Sucofindo Samarinda",
      testType: "Proximate Analysis",
      analysisDate: "2026-03-12",
      parameterName: "Gross Calorific Value (GCV adb)",
      parameterCode: "GCV",
      resultValue: 6250,
      unit: "kcal/kg",
      methodStandard: "ASTM",
      detectionLimit: 10,
      qualityFlag: "PASS",
      certificateRef: "CERT-SUCO-2026-0891",
      validationStatus: "VALID",
      createdAt: "2026-03-12T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
    {
      id: "asy-002",
      companyId: "comp-01",
      siteId: "site-01",
      sampleId: "smp-001",
      sampleCode: "SGT-SMP-001",
      boreholeCode: "BH-SGT-001",
      laboratory: "PT Sucofindo Samarinda",
      testType: "Total Moisture",
      analysisDate: "2026-03-12",
      parameterName: "Total Moisture (TM ar)",
      parameterCode: "TM",
      resultValue: 14.5,
      unit: "%",
      methodStandard: "ASTM",
      detectionLimit: 0.1,
      qualityFlag: "PASS",
      certificateRef: "CERT-SUCO-2026-0891",
      validationStatus: "VALID",
      createdAt: "2026-03-12T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
    {
      id: "asy-003",
      companyId: "comp-01",
      siteId: "site-01",
      sampleId: "smp-001",
      sampleCode: "SGT-SMP-001",
      boreholeCode: "BH-SGT-001",
      laboratory: "PT Sucofindo Samarinda",
      testType: "Inherent Moisture",
      analysisDate: "2026-03-12",
      parameterName: "Inherent Moisture (IM adb)",
      parameterCode: "IM",
      resultValue: 8.2,
      unit: "%",
      methodStandard: "ASTM",
      detectionLimit: 0.1,
      qualityFlag: "PASS",
      certificateRef: "CERT-SUCO-2026-0891",
      validationStatus: "VALID",
      createdAt: "2026-03-12T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
    {
      id: "asy-004",
      companyId: "comp-01",
      siteId: "site-01",
      sampleId: "smp-001",
      sampleCode: "SGT-SMP-001",
      boreholeCode: "BH-SGT-001",
      laboratory: "PT Sucofindo Samarinda",
      testType: "Ash Content",
      analysisDate: "2026-03-12",
      parameterName: "Ash Content (Ash adb)",
      parameterCode: "ASH",
      resultValue: 5.8,
      unit: "%",
      methodStandard: "ASTM",
      detectionLimit: 0.1,
      qualityFlag: "PASS",
      certificateRef: "CERT-SUCO-2026-0891",
      validationStatus: "VALID",
      createdAt: "2026-03-12T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
    {
      id: "asy-005",
      companyId: "comp-01",
      siteId: "site-01",
      sampleId: "smp-001",
      sampleCode: "SGT-SMP-001",
      boreholeCode: "BH-SGT-001",
      laboratory: "PT Sucofindo Samarinda",
      testType: "Total Sulfur",
      analysisDate: "2026-03-12",
      parameterName: "Total Sulfur (TS adb)",
      parameterCode: "TS",
      resultValue: 0.58,
      unit: "%",
      methodStandard: "ASTM",
      detectionLimit: 0.01,
      qualityFlag: "PASS",
      certificateRef: "CERT-SUCO-2026-0891",
      validationStatus: "VALID",
      createdAt: "2026-03-12T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
    {
      id: "asy-006",
      companyId: "comp-01",
      siteId: "site-01",
      sampleId: "smp-001",
      sampleCode: "SGT-SMP-001",
      boreholeCode: "BH-SGT-001",
      laboratory: "PT Sucofindo Samarinda",
      testType: "Volatile Matter",
      analysisDate: "2026-03-12",
      parameterName: "Volatile Matter (VM adb)",
      parameterCode: "VM",
      resultValue: 41.2,
      unit: "%",
      methodStandard: "ASTM",
      detectionLimit: 0.1,
      qualityFlag: "PASS",
      certificateRef: "CERT-SUCO-2026-0891",
      validationStatus: "VALID",
      createdAt: "2026-03-12T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
    {
      id: "asy-007",
      companyId: "comp-01",
      siteId: "site-01",
      sampleId: "smp-001",
      sampleCode: "SGT-SMP-001",
      boreholeCode: "BH-SGT-001",
      laboratory: "PT Sucofindo Samarinda",
      testType: "Fixed Carbon",
      analysisDate: "2026-03-12",
      parameterName: "Fixed Carbon (FC adb)",
      parameterCode: "FC",
      resultValue: 44.8,
      unit: "%",
      methodStandard: "ASTM",
      detectionLimit: 0.1,
      qualityFlag: "PASS",
      certificateRef: "CERT-SUCO-2026-0891",
      validationStatus: "VALID",
      createdAt: "2026-03-12T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
  ];

  // 8. Coal Quality Profiles (Enriched with GAR, GCV, TM, IM, Ash, Sulfur, VM, FC, HGI, AFT)
  private static qualities: CoalQualityProfile[] = [
    {
      id: "cq-001",
      companyId: "comp-01",
      siteId: "site-01",
      sampleId: "smp-001",
      sampleCode: "SGT-SMP-001",
      boreholeCode: "BH-SGT-001",
      seamCode: "SEAM_A",
      fromDepthM: 52.0,
      toDepthM: 58.0,
      thicknessM: 6.0,
      garKcalKg: 5820, // GAR = 6250 * (100-14.5)/(100-8.2)
      gcvAdbKcalKg: 6250,
      cvDafKcalKg: 7267,
      cvArKcalKg: 5820,
      cvDbKcalKg: 6808,
      netCalorificValueNarKcalKg: 5540,
      totalMoistureAr: 14.5,
      inherentMoistureAdb: 8.2,
      ashContentAdb: 5.8,
      ashContentAr: 5.4,
      volatileMatterAdb: 41.2,
      volatileMatterDaf: 47.9,
      fixedCarbonAdb: 44.8,
      fixedCarbonDaf: 52.1,
      totalSulfurAdb: 0.58,
      totalSulfurAr: 0.54,
      pyriticSulfurAdb: 0.12,
      sulfateSulfurAdb: 0.04,
      organicSulfurAdb: 0.42,
      carbonDafPercent: 78.4,
      hydrogenDafPercent: 5.4,
      nitrogenDafPercent: 1.2,
      oxygenDafPercent: 14.3,
      hardgroveGrindabilityIndex: 50,
      relativeDensity: 1.32,
      crucibleSwellingNumberCSN: 1.5,
      ashFusionTemperatureAFT: {
        deformationTempC: 1220,
        sphericalTempC: 1280,
        hemisphericalTempC: 1330,
        fluidTempC: 1390,
        atmosphere: "REDUCING",
      },
      coalRank: "SUB_BITUMINOUS_A",
      complianceGrade: "PREMIUM_EXPORT",
      proximateClosureSum: 100.0, // 8.2 + 5.8 + 41.2 + 44.8 = 100.0
      validationStatus: "VALID",
      isOutlier: false,
      createdAt: "2026-03-14T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
    {
      id: "cq-002",
      companyId: "comp-01",
      siteId: "site-01",
      sampleId: "smp-002",
      sampleCode: "SGT-SMP-002",
      boreholeCode: "BH-SGT-001",
      seamCode: "SEAM_A",
      fromDepthM: 58.0,
      toDepthM: 64.8,
      thicknessM: 6.8,
      garKcalKg: 5735,
      gcvAdbKcalKg: 6180,
      cvDafKcalKg: 7262,
      cvArKcalKg: 5735,
      cvDbKcalKg: 6754,
      netCalorificValueNarKcalKg: 5460,
      totalMoistureAr: 15.1,
      inherentMoistureAdb: 8.5,
      ashContentAdb: 6.4,
      ashContentAr: 5.9,
      volatileMatterAdb: 40.8,
      volatileMatterDaf: 47.9,
      fixedCarbonAdb: 44.3,
      fixedCarbonDaf: 52.1,
      totalSulfurAdb: 0.62,
      totalSulfurAr: 0.58,
      hardgroveGrindabilityIndex: 48,
      relativeDensity: 1.33,
      ashFusionTemperatureAFT: {
        deformationTempC: 1210,
        sphericalTempC: 1270,
        hemisphericalTempC: 1320,
        fluidTempC: 1380,
        atmosphere: "REDUCING",
      },
      coalRank: "SUB_BITUMINOUS_A",
      complianceGrade: "PREMIUM_EXPORT",
      proximateClosureSum: 100.0,
      validationStatus: "VALID",
      isOutlier: false,
      createdAt: "2026-03-14T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
    {
      id: "cq-003",
      companyId: "comp-01",
      siteId: "site-01",
      sampleId: "smp-003",
      sampleCode: "SGT-SMP-003",
      boreholeCode: "BH-SGT-001",
      seamCode: "SEAM_B",
      fromDepthM: 98.0,
      toDepthM: 104.5,
      thicknessM: 6.5,
      garKcalKg: 5240,
      gcvAdbKcalKg: 5720,
      cvDafKcalKg: 7105,
      cvArKcalKg: 5240,
      cvDbKcalKg: 6391,
      netCalorificValueNarKcalKg: 4980,
      totalMoistureAr: 18.2,
      inherentMoistureAdb: 10.5,
      ashContentAdb: 9.0,
      ashContentAr: 8.2,
      volatileMatterAdb: 39.5,
      volatileMatterDaf: 49.1,
      fixedCarbonAdb: 41.0,
      fixedCarbonDaf: 50.9,
      totalSulfurAdb: 1.15,
      totalSulfurAr: 1.05,
      hardgroveGrindabilityIndex: 45,
      relativeDensity: 1.36,
      coalRank: "SUB_BITUMINOUS_B",
      complianceGrade: "HIGH_CV",
      proximateClosureSum: 100.0,
      validationStatus: "VALID",
      isOutlier: false,
      createdAt: "2026-03-14T08:00:00Z",
      updatedAt: "2026-03-14T08:00:00Z",
    },
    {
      id: "cq-004",
      companyId: "comp-01",
      siteId: "site-01",
      sampleId: "smp-004",
      sampleCode: "SGT-SMP-004",
      boreholeCode: "BH-SGT-002",
      seamCode: "SEAM_A",
      fromDepthM: 45.2,
      toDepthM: 57.6,
      thicknessM: 12.4,
      garKcalKg: 5880,
      gcvAdbKcalKg: 6290,
      cvDafKcalKg: 7280,
      cvArKcalKg: 5880,
      cvDbKcalKg: 6837,
      netCalorificValueNarKcalKg: 5600,
      totalMoistureAr: 14.0,
      inherentMoistureAdb: 8.0,
      ashContentAdb: 5.6,
      ashContentAr: 5.2,
      volatileMatterAdb: 41.6,
      volatileMatterDaf: 48.1,
      fixedCarbonAdb: 44.8,
      fixedCarbonDaf: 51.9,
      totalSulfurAdb: 0.52,
      totalSulfurAr: 0.49,
      hardgroveGrindabilityIndex: 52,
      relativeDensity: 1.31,
      coalRank: "SUB_BITUMINOUS_A",
      complianceGrade: "PREMIUM_EXPORT",
      proximateClosureSum: 100.0,
      validationStatus: "VALID",
      isOutlier: false,
      createdAt: "2026-03-18T08:00:00Z",
      updatedAt: "2026-03-18T08:00:00Z",
    },
    {
      id: "cq-005",
      companyId: "comp-01",
      siteId: "site-01",
      sampleId: "smp-005",
      sampleCode: "SGT-SMP-005",
      boreholeCode: "BH-SGT-003",
      seamCode: "SEAM_C",
      fromDepthM: 110.0,
      toDepthM: 114.2,
      thicknessM: 4.2,
      garKcalKg: 4680,
      gcvAdbKcalKg: 5150,
      cvDafKcalKg: 6820,
      cvArKcalKg: 4680,
      cvDbKcalKg: 5852,
      netCalorificValueNarKcalKg: 4390,
      totalMoistureAr: 21.5,
      inherentMoistureAdb: 12.0,
      ashContentAdb: 12.5,
      ashContentAr: 11.1,
      volatileMatterAdb: 37.0,
      volatileMatterDaf: 49.0,
      fixedCarbonAdb: 38.5,
      fixedCarbonDaf: 51.0,
      totalSulfurAdb: 1.85,
      totalSulfurAr: 1.65,
      hardgroveGrindabilityIndex: 42,
      relativeDensity: 1.40,
      coalRank: "SUB_BITUMINOUS_B",
      complianceGrade: "DOMESTIC_PLN",
      proximateClosureSum: 100.0,
      validationStatus: "VALID",
      isOutlier: false,
      createdAt: "2026-04-10T08:00:00Z",
      updatedAt: "2026-04-10T08:00:00Z",
    },
  ];

  // 9. AI Geology Datasets
  private static seamCorrelations: AIGeologySeamCorrelation[] = [
    {
      correlationId: "cor-001",
      boreholePair: ["BH-SGT-001", "BH-SGT-002"],
      sourceSeamCode: "SEAM_A",
      targetSeamCode: "SEAM_A",
      correlationConfidence: 99.2,
      structuralDipCalculatedDeg: 14.2,
      throwDistanceMeters: 0,
      isSplitDetected: false,
      isPinchoutDetected: false,
      aiExplanation: "Kemenerusan stratigrafi Seam A sangat konsisten antara BH-001 dan BH-002 dengan ketebalan 12.4m - 12.8m.",
      suggestedAction: "CONFIRMED_CONTINUITY",
    },
    {
      correlationId: "cor-002",
      boreholePair: ["BH-SGT-002", "BH-SGT-005"],
      sourceSeamCode: "SEAM_A",
      targetSeamCode: "SEAM_A_SPLIT",
      correlationConfidence: 94.5,
      structuralDipCalculatedDeg: 15.0,
      throwDistanceMeters: 0,
      isSplitDetected: true,
      splitDetails: "Seam A terdeteksi mengalami splitting ke arah utara (BH-005) menjadi Seam A1 (7.2m) dan Seam A2 (4.8m) dipisahkan interburden shale 2.4m.",
      isPinchoutDetected: false,
      aiExplanation: "Penebalan interburden shale ke arah utara mengindikasikan sedimentasi channel splay purba.",
      suggestedAction: "SPLIT_MAPPING_REQUIRED",
    },
    {
      correlationId: "cor-003",
      boreholePair: ["BH-SGT-003", "BH-SGT-004"],
      sourceSeamCode: "SEAM_B",
      targetSeamCode: "SEAM_B",
      correlationConfidence: 87.8,
      structuralDipCalculatedDeg: 16.5,
      throwDistanceMeters: 8.5,
      isSplitDetected: false,
      isPinchoutDetected: false,
      aiExplanation: "Terdeteksi offset elevasi floor seam 8.5m yang mengindikasikan adanya Sesar Normal Sangatta North Fault (F-02).",
      suggestedAction: "FAULT_DISPLACEMENT_DETECTED",
    },
  ];

  private static qualityPredictions: AIGeologyQualityPrediction[] = [
    {
      blockId: "BLK-SGT-P1-001",
      targetEasting: 515950.0,
      targetNorthing: 9945550.0,
      targetElevationRL: 30.0,
      seamCode: "SEAM_A",
      predictedGAR: 5850,
      predictedGCVAdb: 6270,
      predictedAsh: 5.7,
      predictedSulfur: 0.55,
      predictedTM: 14.2,
      confidenceScorePercent: 96.8,
      krigingVariance: 0.042,
      nearestSampleDistanceMeters: 110,
      contributingBoreholes: ["BH-SGT-001", "BH-SGT-002"],
      spatialTrendDescription: "Kualitas premium stabil di centroid Pit 1 South dengan nilai Ash < 6.0%.",
    },
    {
      blockId: "BLK-SGT-P1-002",
      targetEasting: 516200.0,
      targetNorthing: 9945400.0,
      targetElevationRL: 15.0,
      seamCode: "SEAM_A",
      predictedGAR: 5790,
      predictedGCVAdb: 6210,
      predictedAsh: 6.2,
      predictedSulfur: 0.60,
      predictedTM: 14.8,
      confidenceScorePercent: 93.4,
      krigingVariance: 0.078,
      nearestSampleDistanceMeters: 145,
      contributingBoreholes: ["BH-SGT-002", "BH-SGT-003"],
      spatialTrendDescription: "Gradien sulfur sedikit meningkat ke arah tenggara namun tetap < 0.8% TS.",
    },
    {
      blockId: "BLK-SGT-P2-001",
      targetEasting: 516800.0,
      targetNorthing: 9946200.0,
      targetElevationRL: -10.0,
      seamCode: "SEAM_B",
      predictedGAR: 5190,
      predictedGCVAdb: 5680,
      predictedAsh: 9.4,
      predictedSulfur: 1.22,
      predictedTM: 18.5,
      confidenceScorePercent: 88.0,
      krigingVariance: 0.125,
      nearestSampleDistanceMeters: 220,
      contributingBoreholes: ["BH-SGT-004", "BH-SGT-005"],
      spatialTrendDescription: "Zona Pit 2 North memerlukan selective mining karena sulfur seam B mendekati 1.3%.",
    },
  ];

  private static anomalies: AIGeologyAnomaly[] = [
    {
      anomalyId: "ANM-001",
      type: "COLLAR_ELEVATION_MISMATCH",
      severity: "HIGH",
      boreholeCode: "BH-SGT-004",
      depthInterval: "Collar Surface (0m)",
      detectedDeviation: "Elevasi Collar (110.0m) selisih +2.2m dari model elevasi LiDAR DTM (107.8m)",
      statisticalZScore: 2.8,
      rootCauseAnalysis: "Pencatatan awal menggunakan Handheld GPS tanpa koreksi base station RTK.",
      mitigationRecommendation: "Lakukan re-survey collar koordinat dan elevasi menggunakan RTK-GPS berkoreksi geoid.",
      status: "OPEN",
    },
    {
      anomalyId: "ANM-002",
      type: "STRUCTURAL_FAULT_THROW",
      severity: "CRITICAL",
      boreholeCode: "BH-SGT-003",
      seamCode: "SEAM_B",
      depthInterval: "98.0m - 104.5m",
      detectedDeviation: "Throw sesar normal 8.5m teridentifikasi di antara BH-003 dan BH-004.",
      statisticalZScore: 3.4,
      rootCauseAnalysis: "Keberadaan zona sesar geser-turun Sangatta North Fault (F-02).",
      mitigationRecommendation: "Tambahkan 2 titik pemboran geoteknik & infill berjarak 30m tegak lurus bidang sesar.",
      status: "OPEN",
    },
    {
      anomalyId: "ANM-003",
      type: "PYRITIC_SULFUR_SPIKE",
      severity: "MEDIUM",
      boreholeCode: "BH-SGT-001",
      seamCode: "SEAM_B",
      depthInterval: "98.0m - 99.2m",
      detectedDeviation: "Sulfur di 1.2m teratas Seam B mencapai 1.85% TS (populasi rata-rata 1.15%).",
      statisticalZScore: 2.1,
      rootCauseAnalysis: "Pengkayaan piritik akibat pengaruh air laut purba (marine transgression) pada lapisan immediate roof.",
      mitigationRecommendation: "Lakukan flitch mining dan blending batubara roof dengan batubara seam A low sulfur.",
      status: "REVIEWED",
    },
  ];

  private static geologicalInterpretation: AIGeologyInterpretation = {
    siteName: "Pit Sangatta 1 South & 2 North",
    depositionalEnvironment: {
      primaryModel: "Lower Delta Plain with Interdistributary Peat Mire",
      faciesAssociations: [
        "Distributary Channel Sandstone (Overburden)",
        "Interdistributary Bay Mudstone / Siltstone (Interburden)",
        "Ombrogenous Coastal Peat Swamp (Seam A Main Coal)",
        "Tidally Influenced Marine-Band Shale (Roof Seam B)",
      ],
      paleocurrentDirection: "South-Southeast (N 165° E)",
      paleochannelRisk: "Rendah pada Seam A (ketebalan stabil), sedang pada Seam B di zona timur laut.",
    },
    structuralFramework: {
      regionalStructure: "Sayap Timur Antiklin Sangatta (Homoklinal Monoklin)",
      averageStrike: "N 025° E",
      averageDip: "14.0° ESE (Kemiringan Landai)",
      majorFaultSystems: [
        "Sangatta Main Boundary Fault (Normal Fault, Dip 65° E, Throw ~15m)",
        "Pit 2 North Cross Fault (Normal-Dextral Strike Slip, Throw ~8.5m)",
      ],
      foldingIntensity: "MILD",
    },
    geologicalSynthesisText:
      "Formasi batubara Sangatta diendapkan pada lingkungan Lower Delta Plain Miosen Awal. Seam A merupakan seam utama berkarakteristik tebal masif (12.4m) dengan kadar abu sangat rendah (<6.0%) dan kalori tinggi (>5,800 kcal/kg GAR). Kemiringan perlapisan 14° ke arah timur tenggara sangat ideal untuk metode penambangan strip mining open pit berjenjang.",
    drillingRecommendations: [
      "Infill Drilling kerapatan 50m x 50m pada blok ekspansi Pushback 2 untuk menaikkan status sumberdaya Indicated ke Measured.",
      "Pengeboran geoteknik inti orientasi (oriented core) di zona sesar Sangatta North Fault.",
      "Uji geokimia Acid Mine Drainage (NAG/NAPP) pada lapisan roof sandstone Seam B.",
    ],
  };

  private static dataValidationSummary: AIGeologyDataValidation = {
    totalRecordsChecked: 1420,
    passedValidationCount: 1398,
    warningCount: 18,
    criticalErrorCount: 4,
    overallIntegrityScorePercent: 98.4,
    checksRun: [
      {
        checkName: "Collar Elevation vs LiDAR DEM Check",
        category: "COLLAR_DEM",
        passed: false,
        issuesFound: 1,
        description: "1 titik bor (BH-SGT-004) memiliki elevasi collar selisih >2.0m dari DTM LiDAR.",
      },
      {
        checkName: "Downhole Interval Overlap & Negative Thickness",
        category: "DEPTH_CONTINUITY",
        passed: true,
        issuesFound: 0,
        description: "Tidak ditemukan tumpang tindih kedalaman atau ketebalan interval bernilai negatif.",
      },
      {
        checkName: "Proximate Analysis 100% Closure (IM + Ash + VM + FC)",
        category: "PROXIMATE_CLOSURE",
        passed: true,
        issuesFound: 0,
        description: "Seluruh 48 sampel laboratorium memenuhi kaidah neraca massa proximate 100.0 ± 0.1%.",
      },
      {
        checkName: "Assay Range & Outlier Detection (CV, Ash, TS)",
        category: "ASSAY_RANGE",
        passed: false,
        issuesFound: 2,
        description: "2 sampel terdeteksi nilai piritik tinggi lokal (TS > 1.8%) pada Seam B.",
      },
      {
        checkName: "Core Recovery vs Sample Log Verification",
        category: "CORE_RECOVERY",
        passed: true,
        issuesFound: 0,
        description: "Tingkat perolehan inti bor (Core Recovery) pada lapisan batubara rata-rata 98.6%.",
      },
      {
        checkName: "Seam Roof < Seam Floor Order Check",
        category: "SEAM_ORDER",
        passed: true,
        issuesFound: 0,
        description: "Elevasi atap (Roof RL) konsisten lebih tinggi dari elevasi lantai (Floor RL).",
      },
    ],
    autoFixableCount: 3,
  };

  private static resourceEstimations: AIGeologyResourceEstimation[] = [
    {
      seamCode: "SEAM_A",
      seamName: "Seam Sangatta A (Main Seam)",
      polygonAreaM2: 1850000, // 185 Hektar
      averageTrueThicknessM: 12.38,
      averageRelativeDensity: 1.32,
      geologicalLossPercent: 5.0,
      inSituMoisturePercent: 14.5,
      inSituTonnageMt: 28.72,
      classificationBreakdown: {
        measuredMt: 18.50, // Radius <= 250m
        indicatedMt: 7.80, // Radius 250 - 500m
        inferredMt: 2.42, // Radius 500 - 1000m
        totalResourceMt: 28.72,
      },
      averageQuality: {
        garKcalKg: 5820,
        gcvAdbKcalKg: 6250,
        tmArPercent: 14.5,
        ashAdbPercent: 5.8,
        tsAdbPercent: 0.58,
        vmAdbPercent: 41.2,
        fcAdbPercent: 44.8,
      },
      competentPersonStatement:
        "Estimasi sumberdaya batubara Seam A telah disusun sesuai Pedoman Pelaporan Hasil Eksplorasi, Sumberdaya dan Cadangan Batubara KCMI 2017 / JORC Code 2012 oleh Competent Person Geologi terdaftar (CPI Geologi No. 2021-CPI-089).",
      complianceStandard: "KCMI_2017",
    },
    {
      seamCode: "SEAM_B",
      seamName: "Seam Sangatta B (Middle Seam)",
      polygonAreaM2: 1720000,
      averageTrueThicknessM: 6.54,
      averageRelativeDensity: 1.35,
      geologicalLossPercent: 7.0,
      inSituMoisturePercent: 18.2,
      inSituTonnageMt: 14.12,
      classificationBreakdown: {
        measuredMt: 8.20,
        indicatedMt: 4.30,
        inferredMt: 1.62,
        totalResourceMt: 14.12,
      },
      averageQuality: {
        garKcalKg: 5240,
        gcvAdbKcalKg: 5720,
        tmArPercent: 18.2,
        ashAdbPercent: 9.0,
        tsAdbPercent: 1.15,
        vmAdbPercent: 39.5,
        fcAdbPercent: 41.0,
      },
      competentPersonStatement:
        "Estimasi sumberdaya Seam B memperhitungkan faktor splitting lokal di sayap utara dan losses geologi 7.0%.",
      complianceStandard: "KCMI_2017",
    },
    {
      seamCode: "SEAM_C",
      seamName: "Seam Sangatta C (Lower Seam)",
      polygonAreaM2: 1450000,
      averageTrueThicknessM: 4.15,
      averageRelativeDensity: 1.39,
      geologicalLossPercent: 8.0,
      inSituMoisturePercent: 21.5,
      inSituTonnageMt: 7.69,
      classificationBreakdown: {
        measuredMt: 3.50,
        indicatedMt: 2.80,
        inferredMt: 1.39,
        totalResourceMt: 7.69,
      },
      averageQuality: {
        garKcalKg: 4680,
        gcvAdbKcalKg: 5150,
        tmArPercent: 21.5,
        ashAdbPercent: 12.5,
        tsAdbPercent: 1.85,
        vmAdbPercent: 37.0,
        fcAdbPercent: 38.5,
      },
      competentPersonStatement:
        "Sumberdaya Seam C dialokasikan untuk kebutuhan PLTU domestik (DMO) dengan proses blending terkontrol.",
      complianceStandard: "KCMI_2017",
    },
  ];

  private static databaseVersions: GeologicalDatabaseVersion[] = [
    {
      id: "gdbv-01",
      companyId: "comp-01",
      siteId: "site-01",
      versionNumber: "v1.0-APPROVED",
      title: "Resmi Baseline Model Geologi Sangatta Q2 2026",
      description: "Database geologi terevaluasi resmi untuk acuan RKAB ESDM 2026.",
      totalBoreholesCount: 24,
      totalSamplesCount: 48,
      status: "APPROVED",
      approvedBy: "Hendra Kusuma (Chief Resource Geologist)",
      approvedAt: "2026-06-01T08:00:00Z",
      createdAt: "2026-05-20T08:00:00Z",
      updatedAt: "2026-06-01T08:00:00Z",
    },
    {
      id: "gdbv-02",
      companyId: "comp-01",
      siteId: "site-01",
      versionNumber: "v2.0-DRAFT",
      title: "Pembaruan Hasil Infill Drilling Q3 2026",
      description: "Draft penambahan titik bor baru di zona Pit 2 North.",
      totalBoreholesCount: 28,
      totalSamplesCount: 56,
      status: "DRAFT",
      createdAt: "2026-08-01T08:00:00Z",
      updatedAt: "2026-08-10T08:00:00Z",
    },
  ];

  private static corePhotos: CorePhotoRecord[] = [
    {
      id: "cp-001",
      companyId: "comp-01",
      siteId: "site-01",
      boreholeId: "bh-001",
      boreholeCode: "BH-SGT-001",
      fromDepth: 50.0,
      toDepth: 55.0,
      boxNumber: 12,
      capturedAt: "2026-03-05T11:00:00Z",
      capturedBy: "Budi Geologist",
      imageUrl: "https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?auto=format&fit=crop&w=800&q=80",
      caption: "Inti Bor Seam Sangatta A (Box 12) - Recovery 100% Bright Coal.",
      createdAt: "2026-03-05T11:00:00Z",
      updatedAt: "2026-03-05T11:00:00Z",
    },
  ];

  // Repository Public API Methods
  public static getBoreholes(): Borehole[] {
    return this.boreholes;
  }

  public static getCollars(): Collar[] {
    return this.collars;
  }

  public static getSurveys(): DownholeSurveyRecord[] {
    return this.surveys;
  }

  public static getLithologyCatalog(): LithologyCatalogItem[] {
    return this.lithologyCatalog;
  }

  public static getLithologies(): LithologyRecord[] {
    return this.lithologies;
  }

  public static getSeamMasters(): SeamMaster[] {
    return this.seamMasters;
  }

  public static getSeamIntersections(): SeamIntersection[] {
    return this.seams;
  }

  public static getSamples(): SampleRecord[] {
    return this.samples;
  }

  public static getAssays(): AssayRecord[] {
    return this.assays;
  }

  public static getQualities(): CoalQualityProfile[] {
    return this.qualities;
  }

  public static getDatabaseVersions(): GeologicalDatabaseVersion[] {
    return this.databaseVersions;
  }

  public static getCorePhotos(): CorePhotoRecord[] {
    return this.corePhotos;
  }

  // AI Geology API Methods
  public static getSeamCorrelations(): AIGeologySeamCorrelation[] {
    return this.seamCorrelations;
  }

  public static getQualityPredictions(): AIGeologyQualityPrediction[] {
    return this.qualityPredictions;
  }

  public static getAnomalies(): AIGeologyAnomaly[] {
    return this.anomalies;
  }

  public static getGeologicalInterpretation(): AIGeologyInterpretation {
    return this.geologicalInterpretation;
  }

  public static getDataValidationSummary(): AIGeologyDataValidation {
    return this.dataValidationSummary;
  }

  public static getResourceEstimations(): AIGeologyResourceEstimation[] {
    return this.resourceEstimations;
  }

  // Mutations
  public static addBorehole(bh: Borehole) {
    this.boreholes = [bh, ...this.boreholes];
  }

  public static addCollar(col: Collar) {
    this.collars = [col, ...this.collars];
  }

  public static addSurvey(survey: DownholeSurveyRecord) {
    this.surveys = [survey, ...this.surveys];
  }

  public static addLithology(lith: LithologyRecord) {
    this.lithologies = [lith, ...this.lithologies];
  }

  public static addSeamIntersection(seam: SeamIntersection) {
    this.seams = [seam, ...this.seams];
  }

  public static addSample(sample: SampleRecord) {
    this.samples = [sample, ...this.samples];
  }

  public static addAssay(assay: AssayRecord) {
    this.assays = [assay, ...this.assays];
  }

  public static addQuality(cq: CoalQualityProfile) {
    this.qualities = [cq, ...this.qualities];
  }

  public static addDatabaseVersion(ver: GeologicalDatabaseVersion) {
    this.databaseVersions = [ver, ...this.databaseVersions];
  }
}
