import { SubscriptionPlanDef } from "../../types/license";

export const SUBSCRIPTION_PLANS: Record<string, SubscriptionPlanDef> = {
  STARTER: {
    planId: "STARTER",
    displayName: "Mine Smart Starter",
    tagline: "Paket dasar operasional tambang skala kecil (IUP Operasi Produksi)",
    priceMonthlyIDR: 15000000, // Rp 15,000,000 / month
    priceQuarterlyIDR: 42000000, // Rp 42,000,000 / quarter (~7% discount)
    priceAnnualIDR: 150000000, // Rp 150,000,000 / year (save 2 months / ~17% discount)
    priceEnterpriseIDR: 180000000, // Custom Enterprise Tier SLA
    maxUsers: 10,
    maxSites: 1,
    maxDevices: 5,
    storageGB: 50,
    aiMonthlyQuota: 1000,
    enabledModules: [
      "dashboard",
      "production",
      "hauling",
      "fleet",
      "fuel",
      "stockpile",
      "hse",
      "reports",
      "ai",
      "users",
      "license",
      "settings",
    ],
    aiFeatures: ["BASIC_QUERY", "PRODUCTION_SUMMARY", "EXECUTIVE_INSIGHTS"],
    supportLevel: "STANDARD",
  },

  PROFESSIONAL: {
    planId: "PROFESSIONAL",
    displayName: "Mine Smart Professional",
    tagline: "Paket komprehensif tambang menengah dengan GIS, FMS Dispatch & Geologi",
    priceMonthlyIDR: 35000000, // Rp 35,000,000 / month
    priceQuarterlyIDR: 98000000, // Rp 98,000,000 / quarter (~7% discount)
    priceAnnualIDR: 350000000, // Rp 350,000,000 / year (save 2 months / ~17% discount)
    priceEnterpriseIDR: 450000000,
    maxUsers: 50,
    maxSites: 3,
    maxDevices: 25,
    storageGB: 250,
    aiMonthlyQuota: 5000,
    enabledModules: [
      "dashboard",
      "ai",
      "gis",
      "mine-planning",
      "geology",
      "survey",
      "fleet",
      "dispatch",
      "production",
      "hauling",
      "fuel",
      "maintenance",
      "stockpile",
      "crusher",
      "laboratory",
      "shipment",
      "hse",
      "environment",
      "reclamation",
      "hr",
      "attendance",
      "procurement",
      "warehouse",
      "finance",
      "reports",
      "analytics",
      "users",
      "roles",
      "license",
      "settings",
      "audit",
    ],
    aiFeatures: [
      "BASIC_QUERY",
      "PRODUCTION_SUMMARY",
      "EXECUTIVE_INSIGHTS",
      "DISPATCH_OPTIMIZER",
      "PREDICTIVE_MAINTENANCE_AI",
      "FUEL_ANOMALY_DETECTOR",
    ],
    supportLevel: "PRIORITY",
  },

  BUSINESS: {
    planId: "BUSINESS",
    displayName: "Mine Smart Business Holding",
    tagline: "Solusi multi-site terintegrasi untuk holding grup tambang besar",
    priceMonthlyIDR: 75000000, // Rp 75,000,000 / month
    priceQuarterlyIDR: 210000000, // Rp 210,000,000 / quarter (~7% discount)
    priceAnnualIDR: 750000000, // Rp 750,000,000 / year (save 2 months / ~17% discount)
    priceEnterpriseIDR: 950000000,
    maxUsers: 200,
    maxSites: 10,
    maxDevices: 100,
    storageGB: 1000,
    aiMonthlyQuota: 25000,
    enabledModules: [
      "dashboard",
      "ai",
      "gis",
      "mine-planning",
      "geology",
      "survey",
      "fleet",
      "dispatch",
      "production",
      "hauling",
      "fuel",
      "maintenance",
      "stockpile",
      "crusher",
      "laboratory",
      "shipment",
      "hse",
      "environment",
      "reclamation",
      "hr",
      "attendance",
      "procurement",
      "warehouse",
      "finance",
      "reports",
      "analytics",
      "users",
      "roles",
      "license",
      "settings",
      "audit",
    ],
    aiFeatures: [
      "ALL_AI_COPILOT_FEATURES",
      "PREDICTIVE_ANALYTICS_AI",
      "AUTOMATED_REPORT_GENERATOR",
      "CUSTOM_PROMPT_ENGINEERING",
    ],
    supportLevel: "PRIORITY",
  },

  ENTERPRISE: {
    planId: "ENTERPRISE",
    displayName: "Mine Smart Unlimited Enterprise",
    tagline: "Edisi khusus enterprise tanpa batas user & site dengan dedicated SLA 24/7",
    priceMonthlyIDR: 150000000, // Rp 150,000,000 / month
    priceQuarterlyIDR: 420000000, // Rp 420,000,000 / quarter (~7% discount)
    priceAnnualIDR: 1500000000, // Rp 1,500,000,000 / year (save 2 months)
    priceEnterpriseIDR: 2500000000, // Multi-holding Enterprise custom
    maxUsers: 1000,
    maxSites: 50,
    maxDevices: 500,
    storageGB: 5000,
    aiMonthlyQuota: 100000,
    enabledModules: [
      "dashboard",
      "ai",
      "gis",
      "mine-planning",
      "geology",
      "survey",
      "fleet",
      "dispatch",
      "production",
      "hauling",
      "fuel",
      "maintenance",
      "stockpile",
      "crusher",
      "laboratory",
      "shipment",
      "hse",
      "environment",
      "reclamation",
      "hr",
      "attendance",
      "procurement",
      "warehouse",
      "finance",
      "reports",
      "analytics",
      "users",
      "roles",
      "license",
      "settings",
      "audit",
    ],
    aiFeatures: [
      "ALL_AI_COPILOT_FEATURES",
      "FINE_TUNED_MINING_LLM",
      "SAP_ERP_DIRECT_INTEGRATION",
      "OFFLINE_EDGE_AI_SYNC",
    ],
    supportLevel: "DEDICATED_24_7",
  },
};
