import React from "react";
import { FileSpreadsheet, Download, FileText, CheckCircle2 } from "lucide-react";
import { LaboratoryReport } from "../../../types/laboratoryTypes";

interface ReportsTabProps {
  reports: LaboratoryReport[];
}

export const ReportsTab: React.FC<ReportsTabProps> = ({ reports }) => {
  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs">
        <div>
          <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
            <FileSpreadsheet className="w-5 h-5 text-emerald-500" /> Pelaporan Kualitas Batubara & Format ESDM
          </h2>
          <p className="text-xs text-slate-500 mt-0.5">
            Laporan ketersediaan assay laboratorium, rekonsiliasi bulanan, serta dokumen siap kirim sesuai standar RKAB & ESDM Form 04.
          </p>
        </div>
      </div>

      <div className="space-y-3">
        {reports.map((rep) => (
          <div
            key={rep.id}
            className="p-5 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-4"
          >
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <span className="font-mono text-xs font-bold text-emerald-500">{rep.reportCode}</span>
                <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300">
                  {rep.format}
                </span>
              </div>
              <h3 className="text-sm font-bold text-slate-900 dark:text-slate-100">{rep.title}</h3>
              <p className="text-xs text-slate-500">
                Periode: {rep.period} • Generated by: {rep.generatedBy} ({rep.generatedAt.slice(0, 10)})
              </p>
            </div>

            <button
              onClick={() => alert(`Mengunduh laporan ${rep.title}...`)}
              className="px-4 py-2 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-emerald-500 hover:text-slate-950 text-slate-700 dark:text-slate-200 font-bold text-xs transition flex items-center gap-2 w-fit"
            >
              <Download className="w-4 h-4" /> Download Report
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};
